In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('telecom_churn_data.csv')
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,...,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
0,7000842753,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,197.385,...,0,1.0,1.0,1.0,NaN,968,30.4,0.0,101.20,3.58
1,7001865778,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,34.047,...,0,NaN,1.0,1.0,NaN,1006,0.0,0.0,0.00,0.00
2,7001625959,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,167.690,...,0,NaN,NaN,NaN,1.0,1103,0.0,0.0,4.17,0.00
3,7001204172,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,221.338,...,0,NaN,NaN,NaN,NaN,2491,0.0,0.0,0.00,0.00
4,7000142493,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,261.636,...,0,0.0,NaN,NaN,NaN,1526,0.0,0.0,0.00,0.00

In [3]:
#!pip install -U jinja2

In [4]:
df.info(max_cols=230)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 226 columns):
 #    Column                    Non-Null Count  Dtype
---   ------                    --------------  -----
 0    mobile_number             99999 non-null  int64
 1    circle_id                 99999 non-null  int64
 2    loc_og_t2o_mou            98981 non-null  float64
 3    std_og_t2o_mou            98981 non-null  float64
 4    loc_ic_t2o_mou            98981 non-null  float64
 5    last_date_of_month_6      99999 non-null  object
 6    last_date_of_month_7      99398 non-null  object
 7    last_date_of_month_8      98899 non-null  object
 8    last_date_of_month_9      98340 non-null  object
 9    arpu_6                    99999 non-null  float64
 10   arpu_7                    99999 non-null  float64
 11   arpu_8                    99999 non-null  float64
 12   arpu_9                    99999 non-null  float64
 13   onnet_mou_6               96062 non-null  float64
 14   onnet_mou_7               96140 non-null  float64
 15   onnet_mou_8               94621 non-null  float64
 16   onnet_mou_9               92254 non-null  float64
 17   offnet_mou_6              96062 non-null  float64
 18   offnet_mou_7              96140 non-null  float64
 19   offnet_mou_8              94621 non-null  float64
 20   offnet_mou_9              92254 non-null  float64
 21   roam_ic_mou_6             96062 non-null  float64
 22   roam_ic_mou_7             96140 non-null  float64
 23   roam_ic_mou_8             94621 non-null  float64
 24   roam_ic_mou_9             92254 non-null  float64
 25   roam_og_mou_6             96062 non-null  float64
 26   roam_og_mou_7             96140 non-null  float64
 27   roam_og_mou_8             94621 non-null  float64
 28   roam_og_mou_9             92254 non-null  float64
 29   loc_og_t2t_mou_6          96062 non-null  float64
 30   loc_og_t2t_mou_7          96140 non-null  float64
 31   loc_og_t2t_mou_8          94621 non-null  float64
 32   loc_og_t2t_mou_9          92254 non-null  float64
 33   loc_og_t2m_mou_6          96062 non-null  float64
 34   loc_og_t2m_mou_7          96140 non-null  float64
 35   loc_og_t2m_mou_8          94621 non-null  float64
 36   loc_og_t2m_mou_9          92254 non-null  float64
 37   loc_og_t2f_mou_6          96062 non-null  float64
 38   loc_og_t2f_mou_7          96140 non-null  float64
 39   loc_og_t2f_mou_8          94621 non-null  float64
 40   loc_og_t2f_mou_9          92254 non-null  float64
 41   loc_og_t2c_mou_6          96062 non-null  float64
 42   loc_og_t2c_mou_7          96140 non-null  float64
 43   loc_og_t2c_mou_8          94621 non-null  float64
 44   loc_og_t2c_mou_9          92254 non-null  float64
 45   loc_og_mou_6              96062 non-null  float64
 46   loc_og_mou_7              96140 non-null  float64
 47   loc_og_mou_8              94621 non-null  float64
 48   loc_og_mou_9              92254 non-null  float64
 49   std_og_t2t_mou_6          96062 non-null  float64
 50   std_og_t2t_mou_7          96140 non-null  float64
 51   std_og_t2t_mou_8          94621 non-null  float64
 52   std_og_t2t_mou_9          92254 non-null  float64
 53   std_og_t2m_mou_6          96062 non-null  float64
 54   std_og_t2m_mou_7          96140 non-null  float64
 55   std_og_t2m_mou_8          94621 non-null  float64
 56   std_og_t2m_mou_9          92254 non-null  float64
 57   std_og_t2f_mou_6          96062 non-null  float64
 58   std_og_t2f_mou_7          96140 non-null  float64
 59   std_og_t2f_mou_8          94621 non-null  float64
 60   std_og_t2f_mou_9          92254 non-null  float64
 61   std_og_t2c_mou_6          96062 non-null  float64
 62   std_og_t2c_mou_7          96140 non-null  float64
 63   std_og_t2c_mou_8          94621 non-null  float64
 64   std_og_t2c_mou_9          92254 non-null  float64
 65   std_og_mou_6              96062 non-null  float64
 66   std_og_mou_7              96140 non-null  float64
 67   std_og_mou_8              94621 non-null  float64
 68   std_og_mou_9              92254 non-null  float64
 69   isd_og_mou_6              96062 non-null  float64
 70   isd_og_mou_7              96140 non-null  float64
 71   isd_og_mou_8              94621 non-null  float64
 72   isd_og_mou_9              92254 non-null  float64
 73   spl_og_mou_6              96062 non-null  float64
 74   spl_og_mou_7              96140 non-null  float64
 75   spl_og_mou_8              94621 non-null  float64
 76   spl_og_mou_9              92254 non-null  float64
 77   og_others_6               96062 non-null  float64
 78   og_others_7               96140 non-null  float64
 79   og_others_8               94621 non-null  float64
 80   og_others_9               92254 non-null  float64
 81   total_og_mou_6            99999 non-null  float64
 82   total_og_mou_7            99999 non-null  float64
 83   total_og_mou_8            99999 non-null  float64
 84   total_og_mou_9            99999 non-null  float64
 85   loc_ic_t2t_mou_6          96062 non-null  float64
 86   loc_ic_t2t_mou_7          96140 non-null  float64
 87   loc_ic_t2t_mou_8          94621 non-null  float64
 88   loc_ic_t2t_mou_9          92254 non-null  float64
 89   loc_ic_t2m_mou_6          96062 non-null  float64
 90   loc_ic_t2m_mou_7          96140 non-null  float64
 91   loc_ic_t2m_mou_8          94621 non-null  float64
 92   loc_ic_t2m_mou_9          92254 non-null  float64
 93   loc_ic_t2f_mou_6          96062 non-null  float64
 94   loc_ic_t2f_mou_7          96140 non-null  float64
 95   loc_ic_t2f_mou_8          94621 non-null  float64
 96   loc_ic_t2f_mou_9          92254 non-null  float64
 97   loc_ic_mou_6              96062 non-null  float64
 98   loc_ic_mou_7              96140 non-null  float64
 99   loc_ic_mou_8              94621 non-null  float64
 100  loc_ic_mou_9              92254 non-null  float64
 101  std_ic_t2t_mou_6          96062 non-null  float64
 102  std_ic_t2t_mou_7          96140 non-null  float64
 103  std_ic_t2t_mou_8          94621 non-null  float64
 104  std_ic_t2t_mou_9          92254 non-null  float64
 105  std_ic_t2m_mou_6          96062 non-null  float64
 106  std_ic_t2m_mou_7          96140 non-null  float64
 107  std_ic_t2m_mou_8          94621 non-null  float64
 108  std_ic_t2m_mou_9          92254 non-null  float64
 109  std_ic_t2f_mou_6          96062 non-null  float64
 110  std_ic_t2f_mou_7          96140 non-null  float64
 111  std_ic_t2f_mou_8          94621 non-null  float64
 112  std_ic_t2f_mou_9          92254 non-null  float64
 113  std_ic_t2o_mou_6          96062 non-null  float64
 114  std_ic_t2o_mou_7          96140 non-null  float64
 115  std_ic_t2o_mou_8          94621 non-null  float64
 116  std_ic_t2o_mou_9          92254 non-null  float64
 117  std_ic_mou_6              96062 non-null  float64
 118  std_ic_mou_7              96140 non-null  float64
 119  std_ic_mou_8              94621 non-null  float64
 120  std_ic_mou_9              92254 non-null  float64
 121  total_ic_mou_6            99999 non-null  float64
 122  total_ic_mou_7            99999 non-null  float64
 123  total_ic_mou_8            99999 non-null  float64
 124  total_ic_mou_9            99999 non-null  float64
 125  spl_ic_mou_6              96062 non-null  float64
 126  spl_ic_mou_7              96140 non-null  float64
 127  spl_ic_mou_8              94621 non-null  float64
 128  spl_ic_mou_9              92254 non-null  float64
 129  isd_ic_mou_6              96062 non-null  float64
 130  isd_ic_mou_7              96140 non-null  float64
 131  isd_ic_mou_8              94621 non-null  float64
 132  isd_ic_mou_9              92254 non-null  float64
 133  ic_others_6               96062 non-null  float64
 134  ic_others_7               96140 non-null  float64
 135  ic_others_8               94621 non-null  float64
 136  ic_others_9               92254 non-null  float64
 137  total_rech_num_6          99999 non-null  int64
 138  total_rech_num_7          99999 non-null  int64
 139  total_rech_num_8          99999 non-null  int64
 140  total_rech_num_9          99999 non-null  int64
 141  total_rech_amt_6          99999 non-null  int64
 142  total_rech_amt_7          99999 non-null  int64
 143  total_rech_amt_8          99999 non-null  int64
 144  total_rech_amt_9          99999 non-null  int64
 145  max_rech_amt_6            99999 non-null  int64
 146  max_rech_amt_7            99999 non-null  int64
 147  max_rech_amt_8            99999 non-null  int64
 148  max_rech_amt_9            99999 non-null  int64
 149  date_of_last_rech_6       98392 non-null  object
 150  date_of_last_rech_7       98232 non-null  object
 151  date_of_last_rech_8       96377 non-null  object
 152  date_of_last_rech_9       95239 non-null  object
 153  last_day_rch_amt_6        99999 non-null  int64
 154  last_day_rch_amt_7        99999 non-null  int64
 155  last_day_rch_amt_8        99999 non-null  int64
 156  last_day_rch_amt_9        99999 non-null  int64
 157  date_of_last_rech_data_6  25153 non-null  object
 158  date_of_last_rech_data_7  25571 non-null  object
 159  date_of_last_rech_data_8  26339 non-null  object
 160  date_of_last_rech_data_9  25922 non-null  object
 161  total_rech_data_6         25153 non-null  float64
 162  total_rech_data_7         25571 non-null  float64
 163  total_rech_data_8         26339 non-null  float64
 164  total_rech_data_9         25922 non-null  float64
 165  max_rech_data_6           25153 non-null  float64
 166  max_rech_data_7           25571 non-null  float64
 167  max_rech_data_8           26339 non-null  float64
 168  max_rech_data_9           25922 non-null  float64
 169  count_rech_2g_6           25153 non-null  float64
 170  count_rech_2g_7           25571 non-null  float64
 171  count_rech_2g_8           26339 non-null  float64
 172  count_rech_2g_9           25922 non-null  float64
 173  count_rech_3g_6           25153 non-null  float64
 174  count_rech_3g_7           25571 non-null  float64
 175  count_rech_3g_8           26339 non-null  float64
 176  count_rech_3g_9           25922 non-null  float64
 177  av_rech_amt_data_6        25153 non-null  float64
 178  av_rech_amt_data_7        25571 non-null  float64
 179  av_rech_amt_data_8        26339 non-null  float64
 180  av_rech_amt_data_9        25922 non-null  float64
 181  vol_2g_mb_6               99999 non-null  float64
 182  vol_2g_mb_7               99999 non-null  float64
 183  vol_2g_mb_8               99999 non-null  float64
 184  vol_2g_mb_9               99999 non-null  float64
 185  vol_3g_mb_6               99999 non-null  float64
 186  vol_3g_mb_7               99999 non-null  float64
 187  vol_3g_mb_8               99999 non-null  float64
 188  vol_3g_mb_9               99999 non-null  float64
 189  arpu_3g_6                 25153 non-null  float64
 190  arpu_3g_7                 25571 non-null  float64
 191  arpu_3g_8                 26339 non-null  float64
 192  arpu_3g_9                 25922 non-null  float64
 193  arpu_2g_6                 25153 non-null  float64
 194  arpu_2g_7                 25571 non-null  float64
 195  arpu_2g_8                 26339 non-null  float64
 196  arpu_2g_9                 25922 non-null  float64
 197  night_pck_user_6          25153 non-null  float64
 198  night_pck_user_7          25571 non-null  float64
 199  night_pck_user_8          26339 non-null  float64
 200  night_pck_user_9          25922 non-null  float64
 201  monthly_2g_6              99999 non-null  int64
 202  monthly_2g_7              99999 non-null  int64
 203  monthly_2g_8              99999 non-null  int64
 204  monthly_2g_9              99999 non-null  int64
 205  sachet_2g_6               99999 non-null  int64
 206  sachet_2g_7               99999 non-null  int64
 207  sachet_2g_8               99999 non-null  int64
 208  sachet_2g_9               99999 non-null  int64
 209  monthly_3g_6              99999 non-null  int64
 210  monthly_3g_7              99999 non-null  int64
 211  monthly_3g_8              99999 non-null  int64
 212  monthly_3g_9              99999 non-null  int64
 213  sachet_3g_6               99999 non-null  int64
 214  sachet_3g_7               99999 non-null  int64
 215  sachet_3g_8               99999 non-null  int64
 216  sachet_3g_9               99999 non-null  int64
 217  fb_user_6                 25153 non-null  float64
 218  fb_user_7                 25571 non-null  float64
 219  fb_user_8                 26339 non-null  float64
 220  fb_user_9                 25922 non-null  float64
 221  aon                       99999 non-null  int64
 222  aug_vbc_3g                99999 non-null  float64
 223  jul_vbc_3g                99999 non-null  float64
 224  jun_vbc_3g                99999 non-null  float64
 225  sep_vbc_3g                99999 non-null  float64
dtypes: float64(179), int64(35), object(12)
memory usage: 172.4+ MB

In [5]:
date_columns = df.filter(regex='date').columns.to_list()

In [6]:
date_columns

['last_date_of_month_6',
 'last_date_of_month_7',
 'last_date_of_month_8',
 'last_date_of_month_9',
 'date_of_last_rech_6',
 'date_of_last_rech_7',
 'date_of_last_rech_8',
 'date_of_last_rech_9',
 'date_of_last_rech_data_6',
 'date_of_last_rech_data_7',
 'date_of_last_rech_data_8',
 'date_of_last_rech_data_9']

In [7]:
df = pd.read_csv('telecom_churn_data.csv',parse_dates=date_columns)

In [8]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,...,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
0,7000842753,109,0.0,0.0,0.0,2014-06-30,2014-07-31,2014-08-31,2014-09-30,197.385,...,0,1.0,1.0,1.0,NaN,968,30.4,0.0,101.20,3.58
1,7001865778,109,0.0,0.0,0.0,2014-06-30,2014-07-31,2014-08-31,2014-09-30,34.047,...,0,NaN,1.0,1.0,NaN,1006,0.0,0.0,0.00,0.00
2,7001625959,109,0.0,0.0,0.0,2014-06-30,2014-07-31,2014-08-31,2014-09-30,167.690,...,0,NaN,NaN,NaN,1.0,1103,0.0,0.0,4.17,0.00
3,7001204172,109,0.0,0.0,0.0,2014-06-30,2014-07-31,2014-08-31,2014-09-30,221.338,...,0,NaN,NaN,NaN,NaN,2491,0.0,0.0,0.00,0.00
4,7000142493,109,0.0,0.0,0.0,2014-06-30,2014-07-31,2014-08-31,2014-09-30,261.636,...,0,0.0,NaN,NaN,NaN,1526,0.0,0.0,0.00,0.00

In [9]:
df[date_columns].dtypes

last_date_of_month_6        datetime64[ns]
last_date_of_month_7        datetime64[ns]
last_date_of_month_8        datetime64[ns]
last_date_of_month_9        datetime64[ns]
date_of_last_rech_6         datetime64[ns]
date_of_last_rech_7         datetime64[ns]
date_of_last_rech_8         datetime64[ns]
date_of_last_rech_9         datetime64[ns]
date_of_last_rech_data_6    datetime64[ns]
date_of_last_rech_data_7    datetime64[ns]
date_of_last_rech_data_8    datetime64[ns]
date_of_last_rech_data_9    datetime64[ns]
dtype: object

In [10]:
# Renaming columns 
df = df.rename({'jun_vbc_3g' : 'vbc_3g_6', 'jul_vbc_3g' : 'vbc_3g_7', 'aug_vbc_3g' : 'vbc_3g_8', 'sep_vbc_3g' : 'vbc_3g_9'}, axis=1)

In [11]:
df.info(max_cols=230)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 226 columns):
 #    Column                    Non-Null Count  Dtype
---   ------                    --------------  -----
 0    mobile_number             99999 non-null  int64
 1    circle_id                 99999 non-null  int64
 2    loc_og_t2o_mou            98981 non-null  float64
 3    std_og_t2o_mou            98981 non-null  float64
 4    loc_ic_t2o_mou            98981 non-null  float64
 5    last_date_of_month_6      99999 non-null  datetime64[ns]
 6    last_date_of_month_7      99398 non-null  datetime64[ns]
 7    last_date_of_month_8      98899 non-null  datetime64[ns]
 8    last_date_of_month_9      98340 non-null  datetime64[ns]
 9    arpu_6                    99999 non-null  float64
 10   arpu_7                    99999 non-null  float64
 11   arpu_8                    99999 non-null  float64
 12   arpu_9                    99999 non-null  float64
 13   onnet_mou_6               96062 non-null  float64
 14   onnet_mou_7               96140 non-null  float64
 15   onnet_mou_8               94621 non-null  float64
 16   onnet_mou_9               92254 non-null  float64
 17   offnet_mou_6              96062 non-null  float64
 18   offnet_mou_7              96140 non-null  float64
 19   offnet_mou_8              94621 non-null  float64
 20   offnet_mou_9              92254 non-null  float64
 21   roam_ic_mou_6             96062 non-null  float64
 22   roam_ic_mou_7             96140 non-null  float64
 23   roam_ic_mou_8             94621 non-null  float64
 24   roam_ic_mou_9             92254 non-null  float64
 25   roam_og_mou_6             96062 non-null  float64
 26   roam_og_mou_7             96140 non-null  float64
 27   roam_og_mou_8             94621 non-null  float64
 28   roam_og_mou_9             92254 non-null  float64
 29   loc_og_t2t_mou_6          96062 non-null  float64
 30   loc_og_t2t_mou_7          96140 non-null  float64
 31   loc_og_t2t_mou_8          94621 non-null  float64
 32   loc_og_t2t_mou_9          92254 non-null  float64
 33   loc_og_t2m_mou_6          96062 non-null  float64
 34   loc_og_t2m_mou_7          96140 non-null  float64
 35   loc_og_t2m_mou_8          94621 non-null  float64
 36   loc_og_t2m_mou_9          92254 non-null  float64
 37   loc_og_t2f_mou_6          96062 non-null  float64
 38   loc_og_t2f_mou_7          96140 non-null  float64
 39   loc_og_t2f_mou_8          94621 non-null  float64
 40   loc_og_t2f_mou_9          92254 non-null  float64
 41   loc_og_t2c_mou_6          96062 non-null  float64
 42   loc_og_t2c_mou_7          96140 non-null  float64
 43   loc_og_t2c_mou_8          94621 non-null  float64
 44   loc_og_t2c_mou_9          92254 non-null  float64
 45   loc_og_mou_6              96062 non-null  float64
 46   loc_og_mou_7              96140 non-null  float64
 47   loc_og_mou_8              94621 non-null  float64
 48   loc_og_mou_9              92254 non-null  float64
 49   std_og_t2t_mou_6          96062 non-null  float64
 50   std_og_t2t_mou_7          96140 non-null  float64
 51   std_og_t2t_mou_8          94621 non-null  float64
 52   std_og_t2t_mou_9          92254 non-null  float64
 53   std_og_t2m_mou_6          96062 non-null  float64
 54   std_og_t2m_mou_7          96140 non-null  float64
 55   std_og_t2m_mou_8          94621 non-null  float64
 56   std_og_t2m_mou_9          92254 non-null  float64
 57   std_og_t2f_mou_6          96062 non-null  float64
 58   std_og_t2f_mou_7          96140 non-null  float64
 59   std_og_t2f_mou_8          94621 non-null  float64
 60   std_og_t2f_mou_9          92254 non-null  float64
 61   std_og_t2c_mou_6          96062 non-null  float64
 62   std_og_t2c_mou_7          96140 non-null  float64
 63   std_og_t2c_mou_8          94621 non-null  float64
 64   std_og_t2c_mou_9          92254 non-null  float64
 65   std_og_mou_6              96062 non-null  float64
 66   std_og_mou_7              96140 non-null  float64
 67   std_og_mou_8              94621 non-null  float64
 68   std_og_mou_9              92254 non-null  float64
 69   isd_og_mou_6              96062 non-null  float64
 70   isd_og_mou_7              96140 non-null  float64
 71   isd_og_mou_8              94621 non-null  float64
 72   isd_og_mou_9              92254 non-null  float64
 73   spl_og_mou_6              96062 non-null  float64
 74   spl_og_mou_7              96140 non-null  float64
 75   spl_og_mou_8              94621 non-null  float64
 76   spl_og_mou_9              92254 non-null  float64
 77   og_others_6               96062 non-null  float64
 78   og_others_7               96140 non-null  float64
 79   og_others_8               94621 non-null  float64
 80   og_others_9               92254 non-null  float64
 81   total_og_mou_6            99999 non-null  float64
 82   total_og_mou_7            99999 non-null  float64
 83   total_og_mou_8            99999 non-null  float64
 84   total_og_mou_9            99999 non-null  float64
 85   loc_ic_t2t_mou_6          96062 non-null  float64
 86   loc_ic_t2t_mou_7          96140 non-null  float64
 87   loc_ic_t2t_mou_8          94621 non-null  float64
 88   loc_ic_t2t_mou_9          92254 non-null  float64
 89   loc_ic_t2m_mou_6          96062 non-null  float64
 90   loc_ic_t2m_mou_7          96140 non-null  float64
 91   loc_ic_t2m_mou_8          94621 non-null  float64
 92   loc_ic_t2m_mou_9          92254 non-null  float64
 93   loc_ic_t2f_mou_6          96062 non-null  float64
 94   loc_ic_t2f_mou_7          96140 non-null  float64
 95   loc_ic_t2f_mou_8          94621 non-null  float64
 96   loc_ic_t2f_mou_9          92254 non-null  float64
 97   loc_ic_mou_6              96062 non-null  float64
 98   loc_ic_mou_7              96140 non-null  float64
 99   loc_ic_mou_8              94621 non-null  float64
 100  loc_ic_mou_9              92254 non-null  float64
 101  std_ic_t2t_mou_6          96062 non-null  float64
 102  std_ic_t2t_mou_7          96140 non-null  float64
 103  std_ic_t2t_mou_8          94621 non-null  float64
 104  std_ic_t2t_mou_9          92254 non-null  float64
 105  std_ic_t2m_mou_6          96062 non-null  float64
 106  std_ic_t2m_mou_7          96140 non-null  float64
 107  std_ic_t2m_mou_8          94621 non-null  float64
 108  std_ic_t2m_mou_9          92254 non-null  float64
 109  std_ic_t2f_mou_6          96062 non-null  float64
 110  std_ic_t2f_mou_7          96140 non-null  float64
 111  std_ic_t2f_mou_8          94621 non-null  float64
 112  std_ic_t2f_mou_9          92254 non-null  float64
 113  std_ic_t2o_mou_6          96062 non-null  float64
 114  std_ic_t2o_mou_7          96140 non-null  float64
 115  std_ic_t2o_mou_8          94621 non-null  float64
 116  std_ic_t2o_mou_9          92254 non-null  float64
 117  std_ic_mou_6              96062 non-null  float64
 118  std_ic_mou_7              96140 non-null  float64
 119  std_ic_mou_8              94621 non-null  float64
 120  std_ic_mou_9              92254 non-null  float64
 121  total_ic_mou_6            99999 non-null  float64
 122  total_ic_mou_7            99999 non-null  float64
 123  total_ic_mou_8            99999 non-null  float64
 124  total_ic_mou_9            99999 non-null  float64
 125  spl_ic_mou_6              96062 non-null  float64
 126  spl_ic_mou_7              96140 non-null  float64
 127  spl_ic_mou_8              94621 non-null  float64
 128  spl_ic_mou_9              92254 non-null  float64
 129  isd_ic_mou_6              96062 non-null  float64
 130  isd_ic_mou_7              96140 non-null  float64
 131  isd_ic_mou_8              94621 non-null  float64
 132  isd_ic_mou_9              92254 non-null  float64
 133  ic_others_6               96062 non-null  float64
 134  ic_others_7               96140 non-null  float64
 135  ic_others_8               94621 non-null  float64
 136  ic_others_9               92254 non-null  float64
 137  total_rech_num_6          99999 non-null  int64
 138  total_rech_num_7          99999 non-null  int64
 139  total_rech_num_8          99999 non-null  int64
 140  total_rech_num_9          99999 non-null  int64
 141  total_rech_amt_6          99999 non-null  int64
 142  total_rech_amt_7          99999 non-null  int64
 143  total_rech_amt_8          99999 non-null  int64
 144  total_rech_amt_9          99999 non-null  int64
 145  max_rech_amt_6            99999 non-null  int64
 146  max_rech_amt_7            99999 non-null  int64
 147  max_rech_amt_8            99999 non-null  int64
 148  max_rech_amt_9            99999 non-null  int64
 149  date_of_last_rech_6       98392 non-null  datetime64[ns]
 150  date_of_last_rech_7       98232 non-null  datetime64[ns]
 151  date_of_last_rech_8       96377 non-null  datetime64[ns]
 152  date_of_last_rech_9       95239 non-null  datetime64[ns]
 153  last_day_rch_amt_6        99999 non-null  int64
 154  last_day_rch_amt_7        99999 non-null  int64
 155  last_day_rch_amt_8        99999 non-null  int64
 156  last_day_rch_amt_9        99999 non-null  int64
 157  date_of_last_rech_data_6  25153 non-null  datetime64[ns]
 158  date_of_last_rech_data_7  25571 non-null  datetime64[ns]
 159  date_of_last_rech_data_8  26339 non-null  datetime64[ns]
 160  date_of_last_rech_data_9  25922 non-null  datetime64[ns]
 161  total_rech_data_6         25153 non-null  float64
 162  total_rech_data_7         25571 non-null  float64
 163  total_rech_data_8         26339 non-null  float64
 164  total_rech_data_9         25922 non-null  float64
 165  max_rech_data_6           25153 non-null  float64
 166  max_rech_data_7           25571 non-null  float64
 167  max_rech_data_8           26339 non-null  float64
 168  max_rech_data_9           25922 non-null  float64
 169  count_rech_2g_6           25153 non-null  float64
 170  count_rech_2g_7           25571 non-null  float64
 171  count_rech_2g_8           26339 non-null  float64
 172  count_rech_2g_9           25922 non-null  float64
 173  count_rech_3g_6           25153 non-null  float64
 174  count_rech_3g_7           25571 non-null  float64
 175  count_rech_3g_8           26339 non-null  float64
 176  count_rech_3g_9           25922 non-null  float64
 177  av_rech_amt_data_6        25153 non-null  float64
 178  av_rech_amt_data_7        25571 non-null  float64
 179  av_rech_amt_data_8        26339 non-null  float64
 180  av_rech_amt_data_9        25922 non-null  float64
 181  vol_2g_mb_6               99999 non-null  float64
 182  vol_2g_mb_7               99999 non-null  float64
 183  vol_2g_mb_8               99999 non-null  float64
 184  vol_2g_mb_9               99999 non-null  float64
 185  vol_3g_mb_6               99999 non-null  float64
 186  vol_3g_mb_7               99999 non-null  float64
 187  vol_3g_mb_8               99999 non-null  float64
 188  vol_3g_mb_9               99999 non-null  float64
 189  arpu_3g_6                 25153 non-null  float64
 190  arpu_3g_7                 25571 non-null  float64
 191  arpu_3g_8                 26339 non-null  float64
 192  arpu_3g_9                 25922 non-null  float64
 193  arpu_2g_6                 25153 non-null  float64
 194  arpu_2g_7                 25571 non-null  float64
 195  arpu_2g_8                 26339 non-null  float64
 196  arpu_2g_9                 25922 non-null  float64
 197  night_pck_user_6          25153 non-null  float64
 198  night_pck_user_7          25571 non-null  float64
 199  night_pck_user_8          26339 non-null  float64
 200  night_pck_user_9          25922 non-null  float64
 201  monthly_2g_6              99999 non-null  int64
 202  monthly_2g_7              99999 non-null  int64
 203  monthly_2g_8              99999 non-null  int64
 204  monthly_2g_9              99999 non-null  int64
 205  sachet_2g_6               99999 non-null  int64
 206  sachet_2g_7               99999 non-null  int64
 207  sachet_2g_8               99999 non-null  int64
 208  sachet_2g_9               99999 non-null  int64
 209  monthly_3g_6              99999 non-null  int64
 210  monthly_3g_7              99999 non-null  int64
 211  monthly_3g_8              99999 non-null  int64
 212  monthly_3g_9              99999 non-null  int64
 213  sachet_3g_6               99999 non-null  int64
 214  sachet_3g_7               99999 non-null  int64
 215  sachet_3g_8               99999 non-null  int64
 216  sachet_3g_9               99999 non-null  int64
 217  fb_user_6                 25153 non-null  float64
 218  fb_user_7                 25571 non-null  float64
 219  fb_user_8                 26339 non-null  float64
 220  fb_user_9                 25922 non-null  float64
 221  aon                       99999 non-null  int64
 222  vbc_3g_8                  99999 non-null  float64
 223  vbc_3g_7                  99999 non-null  float64
 224  vbc_3g_6                  99999 non-null  float64
 225  vbc_3g_9                  99999 non-null  float64
dtypes: datetime64[ns](12), float64(179), int64(35)
memory usage: 172.4 MB

In [12]:
df.nunique()

mobile_number     99999
circle_id             1
loc_og_t2o_mou        1
std_og_t2o_mou        1
loc_ic_t2o_mou        1
                  ...
aon                3489
vbc_3g_8          14676
vbc_3g_7          14162
vbc_3g_6          13312
vbc_3g_9           3720
Length: 226, dtype: int64

In [13]:
cat_columns = [x for x in df.columns if (df[x].nunique()<=30 and df[x].dtype in 
                                         ['int','float'] and df[x].nunique() != 1 ) ]

single_value_columns = [x for x in df.columns if df[x].nunique() == 1]

In [14]:
df[cat_columns].nunique()

count_rech_3g_6     25
count_rech_3g_7     28
count_rech_3g_8     29
count_rech_3g_9     27
night_pck_user_6     2
night_pck_user_7     2
night_pck_user_8     2
night_pck_user_9     2
monthly_2g_6         5
monthly_2g_7         6
monthly_2g_8         6
monthly_2g_9         5
monthly_3g_6        12
monthly_3g_7        15
monthly_3g_8        12
monthly_3g_9        11
sachet_3g_6         25
sachet_3g_7         27
sachet_3g_8         29
sachet_3g_9         27
fb_user_6            2
fb_user_7            2
fb_user_8            2
fb_user_9            2
dtype: int64

In [15]:
df[single_value_columns].nunique()

circle_id               1
loc_og_t2o_mou          1
std_og_t2o_mou          1
loc_ic_t2o_mou          1
last_date_of_month_6    1
last_date_of_month_7    1
last_date_of_month_8    1
last_date_of_month_9    1
std_og_t2c_mou_6        1
std_og_t2c_mou_7        1
std_og_t2c_mou_8        1
std_og_t2c_mou_9        1
std_ic_t2o_mou_6        1
std_ic_t2o_mou_7        1
std_ic_t2o_mou_8        1
std_ic_t2o_mou_9        1
dtype: int64

In [16]:
#dropping single value customers
df.drop(columns=single_value_columns,inplace=True)

In [17]:
df.shape

(99999, 210)

In [18]:
# change datatype of columns with less than 30 unique to object

df[cat_columns] = df[cat_columns].astype('O')

In [19]:
df[cat_columns].dtypes

count_rech_3g_6     object
count_rech_3g_7     object
count_rech_3g_8     object
count_rech_3g_9     object
night_pck_user_6    object
night_pck_user_7    object
night_pck_user_8    object
night_pck_user_9    object
monthly_2g_6        object
monthly_2g_7        object
monthly_2g_8        object
monthly_2g_9        object
monthly_3g_6        object
monthly_3g_7        object
monthly_3g_8        object
monthly_3g_9        object
sachet_3g_6         object
sachet_3g_7         object
sachet_3g_8         object
sachet_3g_9         object
fb_user_6           object
fb_user_7           object
fb_user_8           object
fb_user_9           object
dtype: object

In [20]:
# filtering high value customers

In [21]:
df['total_rech_data_amt_6'] = df['av_rech_amt_data_6'] * df['total_rech_data_6']
df['total_rech_data_amt_7'] = df['av_rech_amt_data_7'] * df['total_rech_data_7']
df['total_rech_data_amt_8'] = df['av_rech_amt_data_8'] * df['total_rech_data_8']
df['total_rech_data_amt_9'] = df['av_rech_amt_data_9'] * df['total_rech_data_9']

df.drop(['total_rech_data_6','total_rech_data_7','total_rech_data_8',
              'total_rech_data_9','av_rech_amt_data_6','av_rech_amt_data_7',
              'av_rech_amt_data_8','av_rech_amt_data_9'],axis = 1,inplace = True)

In [22]:
df_av_recharge_6_7 = (df['total_rech_amt_6'].fillna(0) + df['total_rech_amt_7'].fillna(0) 
                        + df['total_rech_data_amt_6'].fillna(0) + df['total_rech_data_amt_7'].fillna(0))/2

In [23]:
perc = np.percentile(df_av_recharge_6_7, 70.0)

In [24]:
df = df[df_av_recharge_6_7 >= perc]

In [25]:
df.shape

(30001, 206)

In [26]:
# missing values

In [27]:
pd.set_option('display.max_rows',300)
df.isnull().mean()

mobile_number               0.000000
arpu_6                      0.000000
arpu_7                      0.000000
arpu_8                      0.000000
arpu_9                      0.000000
onnet_mou_6                 0.018166
onnet_mou_7                 0.017899
onnet_mou_8                 0.039132
onnet_mou_9                 0.063365
offnet_mou_6                0.018166
offnet_mou_7                0.017899
offnet_mou_8                0.039132
offnet_mou_9                0.063365
roam_ic_mou_6               0.018166
roam_ic_mou_7               0.017899
roam_ic_mou_8               0.039132
roam_ic_mou_9               0.063365
roam_og_mou_6               0.018166
roam_og_mou_7               0.017899
roam_og_mou_8               0.039132
roam_og_mou_9               0.063365
loc_og_t2t_mou_6            0.018166
loc_og_t2t_mou_7            0.017899
loc_og_t2t_mou_8            0.039132
loc_og_t2t_mou_9            0.063365
loc_og_t2m_mou_6            0.018166
loc_og_t2m_mou_7            0.017899
loc_og_t2m_mou_8            0.039132
loc_og_t2m_mou_9            0.063365
loc_og_t2f_mou_6            0.018166
loc_og_t2f_mou_7            0.017899
loc_og_t2f_mou_8            0.039132
loc_og_t2f_mou_9            0.063365
loc_og_t2c_mou_6            0.018166
loc_og_t2c_mou_7            0.017899
loc_og_t2c_mou_8            0.039132
loc_og_t2c_mou_9            0.063365
loc_og_mou_6                0.018166
loc_og_mou_7                0.017899
loc_og_mou_8                0.039132
loc_og_mou_9                0.063365
std_og_t2t_mou_6            0.018166
std_og_t2t_mou_7            0.017899
std_og_t2t_mou_8            0.039132
std_og_t2t_mou_9            0.063365
std_og_t2m_mou_6            0.018166
std_og_t2m_mou_7            0.017899
std_og_t2m_mou_8            0.039132
std_og_t2m_mou_9            0.063365
std_og_t2f_mou_6            0.018166
std_og_t2f_mou_7            0.017899
std_og_t2f_mou_8            0.039132
std_og_t2f_mou_9            0.063365
std_og_mou_6                0.018166
std_og_mou_7                0.017899
std_og_mou_8                0.039132
std_og_mou_9                0.063365
isd_og_mou_6                0.018166
isd_og_mou_7                0.017899
isd_og_mou_8                0.039132
isd_og_mou_9                0.063365
spl_og_mou_6                0.018166
spl_og_mou_7                0.017899
spl_og_mou_8                0.039132
spl_og_mou_9                0.063365
og_others_6                 0.018166
og_others_7                 0.017899
og_others_8                 0.039132
og_others_9                 0.063365
total_og_mou_6              0.000000
total_og_mou_7              0.000000
total_og_mou_8              0.000000
total_og_mou_9              0.000000
loc_ic_t2t_mou_6            0.018166
loc_ic_t2t_mou_7            0.017899
loc_ic_t2t_mou_8            0.039132
loc_ic_t2t_mou_9            0.063365
loc_ic_t2m_mou_6            0.018166
loc_ic_t2m_mou_7            0.017899
loc_ic_t2m_mou_8            0.039132
loc_ic_t2m_mou_9            0.063365
loc_ic_t2f_mou_6            0.018166
loc_ic_t2f_mou_7            0.017899
loc_ic_t2f_mou_8            0.039132
loc_ic_t2f_mou_9            0.063365
loc_ic_mou_6                0.018166
loc_ic_mou_7                0.017899
loc_ic_mou_8                0.039132
loc_ic_mou_9                0.063365
std_ic_t2t_mou_6            0.018166
std_ic_t2t_mou_7            0.017899
std_ic_t2t_mou_8            0.039132
std_ic_t2t_mou_9            0.063365
std_ic_t2m_mou_6            0.018166
std_ic_t2m_mou_7            0.017899
std_ic_t2m_mou_8            0.039132
std_ic_t2m_mou_9            0.063365
std_ic_t2f_mou_6            0.018166
std_ic_t2f_mou_7            0.017899
std_ic_t2f_mou_8            0.039132
std_ic_t2f_mou_9            0.063365
std_ic_mou_6                0.018166
std_ic_mou_7                0.017899
std_ic_mou_8                0.039132
std_ic_mou_9                0.063365
total_ic_mou_6              0.000000
total_ic_mou_7              0.000000
total_ic_mou_8              0.000000
total_ic_mou_9              0.000000
spl_ic_mou_6                0.018166
spl_ic_mou_7                0.017899
spl_ic_mou_8                0.039132
spl_ic_mou_9                0.063365
isd_ic_mou_6                0.018166
isd_ic_mou_7                0.017899
isd_ic_mou_8                0.039132
isd_ic_mou_9                0.063365
ic_others_6                 0.018166
ic_others_7                 0.017899
ic_others_8                 0.039132
ic_others_9                 0.063365
total_rech_num_6            0.000000
total_rech_num_7            0.000000
total_rech_num_8            0.000000
total_rech_num_9            0.000000
total_rech_amt_6            0.000000
total_rech_amt_7            0.000000
total_rech_amt_8            0.000000
total_rech_amt_9            0.000000
max_rech_amt_6              0.000000
max_rech_amt_7              0.000000
max_rech_amt_8              0.000000
max_rech_amt_9              0.000000
date_of_last_rech_6         0.002433
date_of_last_rech_7         0.003267
date_of_last_rech_8         0.019433
date_of_last_rech_9         0.027166
last_day_rch_amt_6          0.000000
last_day_rch_amt_7          0.000000
last_day_rch_amt_8          0.000000
last_day_rch_amt_9          0.000000
date_of_last_rech_data_6    0.441485
date_of_last_rech_data_7    0.431452
date_of_last_rech_data_8    0.468251
date_of_last_rech_data_9    0.492684
max_rech_data_6             0.441485
max_rech_data_7             0.431452
max_rech_data_8             0.468251
max_rech_data_9             0.492684
count_rech_2g_6             0.441485
count_rech_2g_7             0.431452
count_rech_2g_8             0.468251
count_rech_2g_9             0.492684
count_rech_3g_6             0.441485
count_rech_3g_7             0.431452
count_rech_3g_8             0.468251
count_rech_3g_9             0.492684
vol_2g_mb_6                 0.000000
vol_2g_mb_7                 0.000000
vol_2g_mb_8                 0.000000
vol_2g_mb_9                 0.000000
vol_3g_mb_6                 0.000000
vol_3g_mb_7                 0.000000
vol_3g_mb_8                 0.000000
vol_3g_mb_9                 0.000000
arpu_3g_6                   0.441485
arpu_3g_7                   0.431452
arpu_3g_8                   0.468251
arpu_3g_9                   0.492684
arpu_2g_6                   0.441485
arpu_2g_7                   0.431452
arpu_2g_8                   0.468251
arpu_2g_9                   0.492684
night_pck_user_6            0.441485
night_pck_user_7            0.431452
night_pck_user_8            0.468251
night_pck_user_9            0.492684
monthly_2g_6                0.000000
monthly_2g_7                0.000000
monthly_2g_8                0.000000
monthly_2g_9                0.000000
sachet_2g_6                 0.000000
sachet_2g_7                 0.000000
sachet_2g_8                 0.000000
sachet_2g_9                 0.000000
monthly_3g_6                0.000000
monthly_3g_7                0.000000
monthly_3g_8                0.000000
monthly_3g_9                0.000000
sachet_3g_6                 0.000000
sachet_3g_7                 0.000000
sachet_3g_8                 0.000000
sachet_3g_9                 0.000000
fb_user_6                   0.441485
fb_user_7                   0.431452
fb_user_8                   0.468251
fb_user_9                   0.492684
aon                         0.000000
vbc_3g_8                    0.000000
vbc_3g_7                    0.000000
vbc_3g_6                    0.000000
vbc_3g_9                    0.000000
total_rech_data_amt_6       0.441485
total_rech_data_amt_7       0.431452
total_rech_data_amt_8       0.468251
total_rech_data_amt_9       0.492684
dtype: float64

In [28]:
# droping columns with more than 40% missing
drop_col = [x for x in df.columns if df[x].isnull().mean()>0.40]

In [29]:
df.drop(columns=drop_col,inplace=True)

In [30]:
df.shape

(30001, 170)

In [31]:
null = np.round(df.filter(regex='6$').isnull().mean()*100,2)
null = null.to_frame()
null

                        0
arpu_6               0.00
onnet_mou_6          1.82
offnet_mou_6         1.82
roam_ic_mou_6        1.82
roam_og_mou_6        1.82
loc_og_t2t_mou_6     1.82
loc_og_t2m_mou_6     1.82
loc_og_t2f_mou_6     1.82
loc_og_t2c_mou_6     1.82
loc_og_mou_6         1.82
std_og_t2t_mou_6     1.82
std_og_t2m_mou_6     1.82
std_og_t2f_mou_6     1.82
std_og_mou_6         1.82
isd_og_mou_6         1.82
spl_og_mou_6         1.82
og_others_6          1.82
total_og_mou_6       0.00
loc_ic_t2t_mou_6     1.82
loc_ic_t2m_mou_6     1.82
loc_ic_t2f_mou_6     1.82
loc_ic_mou_6         1.82
std_ic_t2t_mou_6     1.82
std_ic_t2m_mou_6     1.82
std_ic_t2f_mou_6     1.82
std_ic_mou_6         1.82
total_ic_mou_6       0.00
spl_ic_mou_6         1.82
isd_ic_mou_6         1.82
ic_others_6          1.82
total_rech_num_6     0.00
total_rech_amt_6     0.00
max_rech_amt_6       0.00
date_of_last_rech_6  0.24
last_day_rch_amt_6   0.00
vol_2g_mb_6          0.00
vol_3g_mb_6          0.00
monthly_2g_6         0.00
sachet_2g_6          0.00
monthly_3g_6         0.00
sachet_3g_6          0.00
vbc_3g_6             0.00

In [32]:
null_random = ['date_of_last_rech_6']

In [33]:
col = list(null.index[list((null == 1.82)[0].values)])

In [34]:
df[col].isnull().mean()

onnet_mou_6         0.018166
offnet_mou_6        0.018166
roam_ic_mou_6       0.018166
roam_og_mou_6       0.018166
loc_og_t2t_mou_6    0.018166
loc_og_t2m_mou_6    0.018166
loc_og_t2f_mou_6    0.018166
loc_og_t2c_mou_6    0.018166
loc_og_mou_6        0.018166
std_og_t2t_mou_6    0.018166
std_og_t2m_mou_6    0.018166
std_og_t2f_mou_6    0.018166
std_og_mou_6        0.018166
isd_og_mou_6        0.018166
spl_og_mou_6        0.018166
og_others_6         0.018166
loc_ic_t2t_mou_6    0.018166
loc_ic_t2m_mou_6    0.018166
loc_ic_t2f_mou_6    0.018166
loc_ic_mou_6        0.018166
std_ic_t2t_mou_6    0.018166
std_ic_t2m_mou_6    0.018166
std_ic_t2f_mou_6    0.018166
std_ic_mou_6        0.018166
spl_ic_mou_6        0.018166
isd_ic_mou_6        0.018166
ic_others_6         0.018166
dtype: float64

In [35]:
df.loc[df[col].isnull().sum(axis=1) ==27][['total_og_mou_6','total_ic_mou_6']].sum()

total_og_mou_6    0.0
total_ic_mou_6    0.0
dtype: float64

In [36]:
df[col] = df[col].fillna(0)

In [37]:
df[col].isnull().mean()

onnet_mou_6         0.0
offnet_mou_6        0.0
roam_ic_mou_6       0.0
roam_og_mou_6       0.0
loc_og_t2t_mou_6    0.0
loc_og_t2m_mou_6    0.0
loc_og_t2f_mou_6    0.0
loc_og_t2c_mou_6    0.0
loc_og_mou_6        0.0
std_og_t2t_mou_6    0.0
std_og_t2m_mou_6    0.0
std_og_t2f_mou_6    0.0
std_og_mou_6        0.0
isd_og_mou_6        0.0
spl_og_mou_6        0.0
og_others_6         0.0
loc_ic_t2t_mou_6    0.0
loc_ic_t2m_mou_6    0.0
loc_ic_t2f_mou_6    0.0
loc_ic_mou_6        0.0
std_ic_t2t_mou_6    0.0
std_ic_t2m_mou_6    0.0
std_ic_t2f_mou_6    0.0
std_ic_mou_6        0.0
spl_ic_mou_6        0.0
isd_ic_mou_6        0.0
ic_others_6         0.0
dtype: float64

In [38]:
null = np.round(df.filter(regex='7$').isnull().mean()*100,2)
null = null.to_frame()
null

                        0
arpu_7               0.00
onnet_mou_7          1.79
offnet_mou_7         1.79
roam_ic_mou_7        1.79
roam_og_mou_7        1.79
loc_og_t2t_mou_7     1.79
loc_og_t2m_mou_7     1.79
loc_og_t2f_mou_7     1.79
loc_og_t2c_mou_7     1.79
loc_og_mou_7         1.79
std_og_t2t_mou_7     1.79
std_og_t2m_mou_7     1.79
std_og_t2f_mou_7     1.79
std_og_mou_7         1.79
isd_og_mou_7         1.79
spl_og_mou_7         1.79
og_others_7          1.79
total_og_mou_7       0.00
loc_ic_t2t_mou_7     1.79
loc_ic_t2m_mou_7     1.79
loc_ic_t2f_mou_7     1.79
loc_ic_mou_7         1.79
std_ic_t2t_mou_7     1.79
std_ic_t2m_mou_7     1.79
std_ic_t2f_mou_7     1.79
std_ic_mou_7         1.79
total_ic_mou_7       0.00
spl_ic_mou_7         1.79
isd_ic_mou_7         1.79
ic_others_7          1.79
total_rech_num_7     0.00
total_rech_amt_7     0.00
max_rech_amt_7       0.00
date_of_last_rech_7  0.33
last_day_rch_amt_7   0.00
vol_2g_mb_7          0.00
vol_3g_mb_7          0.00
monthly_2g_7         0.00
sachet_2g_7          0.00
monthly_3g_7         0.00
sachet_3g_7          0.00
vbc_3g_7             0.00

In [39]:
null_random.append('date_of_last_rech_7')
null_random

['date_of_last_rech_6', 'date_of_last_rech_7']

In [40]:
col = list(null.index[list((null == 1.79)[0].values)])

In [41]:
df[col].isnull().mean()

onnet_mou_7         0.017899
offnet_mou_7        0.017899
roam_ic_mou_7       0.017899
roam_og_mou_7       0.017899
loc_og_t2t_mou_7    0.017899
loc_og_t2m_mou_7    0.017899
loc_og_t2f_mou_7    0.017899
loc_og_t2c_mou_7    0.017899
loc_og_mou_7        0.017899
std_og_t2t_mou_7    0.017899
std_og_t2m_mou_7    0.017899
std_og_t2f_mou_7    0.017899
std_og_mou_7        0.017899
isd_og_mou_7        0.017899
spl_og_mou_7        0.017899
og_others_7         0.017899
loc_ic_t2t_mou_7    0.017899
loc_ic_t2m_mou_7    0.017899
loc_ic_t2f_mou_7    0.017899
loc_ic_mou_7        0.017899
std_ic_t2t_mou_7    0.017899
std_ic_t2m_mou_7    0.017899
std_ic_t2f_mou_7    0.017899
std_ic_mou_7        0.017899
spl_ic_mou_7        0.017899
isd_ic_mou_7        0.017899
ic_others_7         0.017899
dtype: float64

In [42]:
len(col)

27

In [43]:
df.loc[df[col].isnull().sum(axis=1) ==27][['total_og_mou_7','total_ic_mou_7']].sum()

total_og_mou_7    0.0
total_ic_mou_7    0.0
dtype: float64

In [44]:
df[col] = df[col].fillna(0)

In [45]:
df[col].isnull().mean()

onnet_mou_7         0.0
offnet_mou_7        0.0
roam_ic_mou_7       0.0
roam_og_mou_7       0.0
loc_og_t2t_mou_7    0.0
loc_og_t2m_mou_7    0.0
loc_og_t2f_mou_7    0.0
loc_og_t2c_mou_7    0.0
loc_og_mou_7        0.0
std_og_t2t_mou_7    0.0
std_og_t2m_mou_7    0.0
std_og_t2f_mou_7    0.0
std_og_mou_7        0.0
isd_og_mou_7        0.0
spl_og_mou_7        0.0
og_others_7         0.0
loc_ic_t2t_mou_7    0.0
loc_ic_t2m_mou_7    0.0
loc_ic_t2f_mou_7    0.0
loc_ic_mou_7        0.0
std_ic_t2t_mou_7    0.0
std_ic_t2m_mou_7    0.0
std_ic_t2f_mou_7    0.0
std_ic_mou_7        0.0
spl_ic_mou_7        0.0
isd_ic_mou_7        0.0
ic_others_7         0.0
dtype: float64

In [46]:
null = np.round(df.filter(regex='8$').isnull().mean()*100,2)
null = null.to_frame()
null

                        0
arpu_8               0.00
onnet_mou_8          3.91
offnet_mou_8         3.91
roam_ic_mou_8        3.91
roam_og_mou_8        3.91
loc_og_t2t_mou_8     3.91
loc_og_t2m_mou_8     3.91
loc_og_t2f_mou_8     3.91
loc_og_t2c_mou_8     3.91
loc_og_mou_8         3.91
std_og_t2t_mou_8     3.91
std_og_t2m_mou_8     3.91
std_og_t2f_mou_8     3.91
std_og_mou_8         3.91
isd_og_mou_8         3.91
spl_og_mou_8         3.91
og_others_8          3.91
total_og_mou_8       0.00
loc_ic_t2t_mou_8     3.91
loc_ic_t2m_mou_8     3.91
loc_ic_t2f_mou_8     3.91
loc_ic_mou_8         3.91
std_ic_t2t_mou_8     3.91
std_ic_t2m_mou_8     3.91
std_ic_t2f_mou_8     3.91
std_ic_mou_8         3.91
total_ic_mou_8       0.00
spl_ic_mou_8         3.91
isd_ic_mou_8         3.91
ic_others_8          3.91
total_rech_num_8     0.00
total_rech_amt_8     0.00
max_rech_amt_8       0.00
date_of_last_rech_8  1.94
last_day_rch_amt_8   0.00
vol_2g_mb_8          0.00
vol_3g_mb_8          0.00
monthly_2g_8         0.00
sachet_2g_8          0.00
monthly_3g_8         0.00
sachet_3g_8          0.00
vbc_3g_8             0.00

In [47]:
null_random.append('date_of_last_rech_8')
null_random

['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8']

In [48]:
col = list(null.index[list((null == 3.91)[0].values)])

In [49]:
df[col].isnull().mean()

onnet_mou_8         0.039132
offnet_mou_8        0.039132
roam_ic_mou_8       0.039132
roam_og_mou_8       0.039132
loc_og_t2t_mou_8    0.039132
loc_og_t2m_mou_8    0.039132
loc_og_t2f_mou_8    0.039132
loc_og_t2c_mou_8    0.039132
loc_og_mou_8        0.039132
std_og_t2t_mou_8    0.039132
std_og_t2m_mou_8    0.039132
std_og_t2f_mou_8    0.039132
std_og_mou_8        0.039132
isd_og_mou_8        0.039132
spl_og_mou_8        0.039132
og_others_8         0.039132
loc_ic_t2t_mou_8    0.039132
loc_ic_t2m_mou_8    0.039132
loc_ic_t2f_mou_8    0.039132
loc_ic_mou_8        0.039132
std_ic_t2t_mou_8    0.039132
std_ic_t2m_mou_8    0.039132
std_ic_t2f_mou_8    0.039132
std_ic_mou_8        0.039132
spl_ic_mou_8        0.039132
isd_ic_mou_8        0.039132
ic_others_8         0.039132
dtype: float64

In [50]:
len(col)

27

In [51]:
df.loc[df[col].isnull().sum(axis=1) ==27][['total_og_mou_8','total_ic_mou_8']].sum()

total_og_mou_8    0.0
total_ic_mou_8    0.0
dtype: float64

In [52]:
df[col] = df[col].fillna(0)

In [53]:
df[col].isnull().mean()

onnet_mou_8         0.0
offnet_mou_8        0.0
roam_ic_mou_8       0.0
roam_og_mou_8       0.0
loc_og_t2t_mou_8    0.0
loc_og_t2m_mou_8    0.0
loc_og_t2f_mou_8    0.0
loc_og_t2c_mou_8    0.0
loc_og_mou_8        0.0
std_og_t2t_mou_8    0.0
std_og_t2m_mou_8    0.0
std_og_t2f_mou_8    0.0
std_og_mou_8        0.0
isd_og_mou_8        0.0
spl_og_mou_8        0.0
og_others_8         0.0
loc_ic_t2t_mou_8    0.0
loc_ic_t2m_mou_8    0.0
loc_ic_t2f_mou_8    0.0
loc_ic_mou_8        0.0
std_ic_t2t_mou_8    0.0
std_ic_t2m_mou_8    0.0
std_ic_t2f_mou_8    0.0
std_ic_mou_8        0.0
spl_ic_mou_8        0.0
isd_ic_mou_8        0.0
ic_others_8         0.0
dtype: float64

In [54]:
null = np.round(df.filter(regex='9$').isnull().mean()*100,2)
null = null.to_frame()
null

                        0
arpu_9               0.00
onnet_mou_9          6.34
offnet_mou_9         6.34
roam_ic_mou_9        6.34
roam_og_mou_9        6.34
loc_og_t2t_mou_9     6.34
loc_og_t2m_mou_9     6.34
loc_og_t2f_mou_9     6.34
loc_og_t2c_mou_9     6.34
loc_og_mou_9         6.34
std_og_t2t_mou_9     6.34
std_og_t2m_mou_9     6.34
std_og_t2f_mou_9     6.34
std_og_mou_9         6.34
isd_og_mou_9         6.34
spl_og_mou_9         6.34
og_others_9          6.34
total_og_mou_9       0.00
loc_ic_t2t_mou_9     6.34
loc_ic_t2m_mou_9     6.34
loc_ic_t2f_mou_9     6.34
loc_ic_mou_9         6.34
std_ic_t2t_mou_9     6.34
std_ic_t2m_mou_9     6.34
std_ic_t2f_mou_9     6.34
std_ic_mou_9         6.34
total_ic_mou_9       0.00
spl_ic_mou_9         6.34
isd_ic_mou_9         6.34
ic_others_9          6.34
total_rech_num_9     0.00
total_rech_amt_9     0.00
max_rech_amt_9       0.00
date_of_last_rech_9  2.72
last_day_rch_amt_9   0.00
vol_2g_mb_9          0.00
vol_3g_mb_9          0.00
monthly_2g_9         0.00
sachet_2g_9          0.00
monthly_3g_9         0.00
sachet_3g_9          0.00
vbc_3g_9             0.00

In [55]:
null_random.append('date_of_last_rech_9')
null_random

['date_of_last_rech_6',
 'date_of_last_rech_7',
 'date_of_last_rech_8',
 'date_of_last_rech_9']

In [56]:
col = list(null.index[list((null == 6.34)[0].values)])

In [57]:
df[col].isnull().mean()

onnet_mou_9         0.063365
offnet_mou_9        0.063365
roam_ic_mou_9       0.063365
roam_og_mou_9       0.063365
loc_og_t2t_mou_9    0.063365
loc_og_t2m_mou_9    0.063365
loc_og_t2f_mou_9    0.063365
loc_og_t2c_mou_9    0.063365
loc_og_mou_9        0.063365
std_og_t2t_mou_9    0.063365
std_og_t2m_mou_9    0.063365
std_og_t2f_mou_9    0.063365
std_og_mou_9        0.063365
isd_og_mou_9        0.063365
spl_og_mou_9        0.063365
og_others_9         0.063365
loc_ic_t2t_mou_9    0.063365
loc_ic_t2m_mou_9    0.063365
loc_ic_t2f_mou_9    0.063365
loc_ic_mou_9        0.063365
std_ic_t2t_mou_9    0.063365
std_ic_t2m_mou_9    0.063365
std_ic_t2f_mou_9    0.063365
std_ic_mou_9        0.063365
spl_ic_mou_9        0.063365
isd_ic_mou_9        0.063365
ic_others_9         0.063365
dtype: float64

In [58]:
len(col)

27

In [59]:
df.loc[df[col].isnull().sum(axis=1) ==27][['total_og_mou_9','total_ic_mou_9']].sum()

total_og_mou_9    0.0
total_ic_mou_9    0.0
dtype: float64

In [60]:
df[col] = df[col].fillna(0)

In [61]:
df[col].isnull().mean()

onnet_mou_9         0.0
offnet_mou_9        0.0
roam_ic_mou_9       0.0
roam_og_mou_9       0.0
loc_og_t2t_mou_9    0.0
loc_og_t2m_mou_9    0.0
loc_og_t2f_mou_9    0.0
loc_og_t2c_mou_9    0.0
loc_og_mou_9        0.0
std_og_t2t_mou_9    0.0
std_og_t2m_mou_9    0.0
std_og_t2f_mou_9    0.0
std_og_mou_9        0.0
isd_og_mou_9        0.0
spl_og_mou_9        0.0
og_others_9         0.0
loc_ic_t2t_mou_9    0.0
loc_ic_t2m_mou_9    0.0
loc_ic_t2f_mou_9    0.0
loc_ic_mou_9        0.0
std_ic_t2t_mou_9    0.0
std_ic_t2m_mou_9    0.0
std_ic_t2f_mou_9    0.0
std_ic_mou_9        0.0
spl_ic_mou_9        0.0
isd_ic_mou_9        0.0
ic_others_9         0.0
dtype: float64

In [62]:
df[null_random].isnull().mean()

date_of_last_rech_6    0.002433
date_of_last_rech_7    0.003267
date_of_last_rech_8    0.019433
date_of_last_rech_9    0.027166
dtype: float64

In [63]:
# Imputing last_date_of_month_* values
df[null_random[0]] = df[null_random[0]].fillna(df[null_random[0]].mode()[0])
df[null_random[1]] = df[null_random[1]].fillna(df[null_random[1]].mode()[0])
df[null_random[2]] = df[null_random[2]].fillna(df[null_random[2]].mode()[0])
df[null_random[3]] = df[null_random[3]].fillna(df[null_random[3]].mode()[0])

In [64]:
df.isnull().mean()

mobile_number          0.0
arpu_6                 0.0
arpu_7                 0.0
arpu_8                 0.0
arpu_9                 0.0
onnet_mou_6            0.0
onnet_mou_7            0.0
onnet_mou_8            0.0
onnet_mou_9            0.0
offnet_mou_6           0.0
offnet_mou_7           0.0
offnet_mou_8           0.0
offnet_mou_9           0.0
roam_ic_mou_6          0.0
roam_ic_mou_7          0.0
roam_ic_mou_8          0.0
roam_ic_mou_9          0.0
roam_og_mou_6          0.0
roam_og_mou_7          0.0
roam_og_mou_8          0.0
roam_og_mou_9          0.0
loc_og_t2t_mou_6       0.0
loc_og_t2t_mou_7       0.0
loc_og_t2t_mou_8       0.0
loc_og_t2t_mou_9       0.0
loc_og_t2m_mou_6       0.0
loc_og_t2m_mou_7       0.0
loc_og_t2m_mou_8       0.0
loc_og_t2m_mou_9       0.0
loc_og_t2f_mou_6       0.0
loc_og_t2f_mou_7       0.0
loc_og_t2f_mou_8       0.0
loc_og_t2f_mou_9       0.0
loc_og_t2c_mou_6       0.0
loc_og_t2c_mou_7       0.0
loc_og_t2c_mou_8       0.0
loc_og_t2c_mou_9       0.0
loc_og_mou_6           0.0
loc_og_mou_7           0.0
loc_og_mou_8           0.0
loc_og_mou_9           0.0
std_og_t2t_mou_6       0.0
std_og_t2t_mou_7       0.0
std_og_t2t_mou_8       0.0
std_og_t2t_mou_9       0.0
std_og_t2m_mou_6       0.0
std_og_t2m_mou_7       0.0
std_og_t2m_mou_8       0.0
std_og_t2m_mou_9       0.0
std_og_t2f_mou_6       0.0
std_og_t2f_mou_7       0.0
std_og_t2f_mou_8       0.0
std_og_t2f_mou_9       0.0
std_og_mou_6           0.0
std_og_mou_7           0.0
std_og_mou_8           0.0
std_og_mou_9           0.0
isd_og_mou_6           0.0
isd_og_mou_7           0.0
isd_og_mou_8           0.0
isd_og_mou_9           0.0
spl_og_mou_6           0.0
spl_og_mou_7           0.0
spl_og_mou_8           0.0
spl_og_mou_9           0.0
og_others_6            0.0
og_others_7            0.0
og_others_8            0.0
og_others_9            0.0
total_og_mou_6         0.0
total_og_mou_7         0.0
total_og_mou_8         0.0
total_og_mou_9         0.0
loc_ic_t2t_mou_6       0.0
loc_ic_t2t_mou_7       0.0
loc_ic_t2t_mou_8       0.0
loc_ic_t2t_mou_9       0.0
loc_ic_t2m_mou_6       0.0
loc_ic_t2m_mou_7       0.0
loc_ic_t2m_mou_8       0.0
loc_ic_t2m_mou_9       0.0
loc_ic_t2f_mou_6       0.0
loc_ic_t2f_mou_7       0.0
loc_ic_t2f_mou_8       0.0
loc_ic_t2f_mou_9       0.0
loc_ic_mou_6           0.0
loc_ic_mou_7           0.0
loc_ic_mou_8           0.0
loc_ic_mou_9           0.0
std_ic_t2t_mou_6       0.0
std_ic_t2t_mou_7       0.0
std_ic_t2t_mou_8       0.0
std_ic_t2t_mou_9       0.0
std_ic_t2m_mou_6       0.0
std_ic_t2m_mou_7       0.0
std_ic_t2m_mou_8       0.0
std_ic_t2m_mou_9       0.0
std_ic_t2f_mou_6       0.0
std_ic_t2f_mou_7       0.0
std_ic_t2f_mou_8       0.0
std_ic_t2f_mou_9       0.0
std_ic_mou_6           0.0
std_ic_mou_7           0.0
std_ic_mou_8           0.0
std_ic_mou_9           0.0
total_ic_mou_6         0.0
total_ic_mou_7         0.0
total_ic_mou_8         0.0
total_ic_mou_9         0.0
spl_ic_mou_6           0.0
spl_ic_mou_7           0.0
spl_ic_mou_8           0.0
spl_ic_mou_9           0.0
isd_ic_mou_6           0.0
isd_ic_mou_7           0.0
isd_ic_mou_8           0.0
isd_ic_mou_9           0.0
ic_others_6            0.0
ic_others_7            0.0
ic_others_8            0.0
ic_others_9            0.0
total_rech_num_6       0.0
total_rech_num_7       0.0
total_rech_num_8       0.0
total_rech_num_9       0.0
total_rech_amt_6       0.0
total_rech_amt_7       0.0
total_rech_amt_8       0.0
total_rech_amt_9       0.0
max_rech_amt_6         0.0
max_rech_amt_7         0.0
max_rech_amt_8         0.0
max_rech_amt_9         0.0
date_of_last_rech_6    0.0
date_of_last_rech_7    0.0
date_of_last_rech_8    0.0
date_of_last_rech_9    0.0
last_day_rch_amt_6     0.0
last_day_rch_amt_7     0.0
last_day_rch_amt_8     0.0
last_day_rch_amt_9     0.0
vol_2g_mb_6            0.0
vol_2g_mb_7            0.0
vol_2g_mb_8            0.0
vol_2g_mb_9            0.0
vol_3g_mb_6            0.0
vol_3g_mb_7            0.0
vol_3g_mb_8            0.0
vol_3g_mb_9            0.0
monthly_2g_6           0.0
monthly_2g_7           0.0
monthly_2g_8           0.0
monthly_2g_9           0.0
sachet_2g_6            0.0
sachet_2g_7            0.0
sachet_2g_8            0.0
sachet_2g_9            0.0
monthly_3g_6           0.0
monthly_3g_7           0.0
monthly_3g_8           0.0
monthly_3g_9           0.0
sachet_3g_6            0.0
sachet_3g_7            0.0
sachet_3g_8            0.0
sachet_3g_9            0.0
aon                    0.0
vbc_3g_8               0.0
vbc_3g_7               0.0
vbc_3g_6               0.0
vbc_3g_9               0.0
dtype: float64

In [65]:
# making a target column

df['Churn'] = 0
churned_customers = df.query('total_og_mou_9 == 0 & total_ic_mou_9 == 0 & vol_2g_mb_9 == 0 &  vol_3g_mb_9 == 0').index
df.loc[churned_customers,'Churn']=1
df['Churn'] = df['Churn'].astype('object')

In [66]:
df.shape

(30001, 171)

In [67]:
df['Churn'].value_counts(normalize=True)

0    0.918636
1    0.081364
Name: Churn, dtype: float64

In [68]:
# dropping columns releted to 9th month

churn_phase_columns = df.filter(regex='9$').columns
df.drop(columns=churn_phase_columns, inplace=True)

In [69]:
df.shape

(30001, 129)

In [70]:
df.drop(columns=['mobile_number'],inplace=True)

In [71]:
#stop

# EDA

In [72]:
df.info(max_cols=130)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30001 entries, 0 to 99997
Data columns (total 128 columns):
 #    Column               Non-Null Count  Dtype
---   ------               --------------  -----
 0    arpu_6               30001 non-null  float64
 1    arpu_7               30001 non-null  float64
 2    arpu_8               30001 non-null  float64
 3    onnet_mou_6          30001 non-null  float64
 4    onnet_mou_7          30001 non-null  float64
 5    onnet_mou_8          30001 non-null  float64
 6    offnet_mou_6         30001 non-null  float64
 7    offnet_mou_7         30001 non-null  float64
 8    offnet_mou_8         30001 non-null  float64
 9    roam_ic_mou_6        30001 non-null  float64
 10   roam_ic_mou_7        30001 non-null  float64
 11   roam_ic_mou_8        30001 non-null  float64
 12   roam_og_mou_6        30001 non-null  float64
 13   roam_og_mou_7        30001 non-null  float64
 14   roam_og_mou_8        30001 non-null  float64
 15   loc_og_t2t_mou_6     30001 non-null  float64
 16   loc_og_t2t_mou_7     30001 non-null  float64
 17   loc_og_t2t_mou_8     30001 non-null  float64
 18   loc_og_t2m_mou_6     30001 non-null  float64
 19   loc_og_t2m_mou_7     30001 non-null  float64
 20   loc_og_t2m_mou_8     30001 non-null  float64
 21   loc_og_t2f_mou_6     30001 non-null  float64
 22   loc_og_t2f_mou_7     30001 non-null  float64
 23   loc_og_t2f_mou_8     30001 non-null  float64
 24   loc_og_t2c_mou_6     30001 non-null  float64
 25   loc_og_t2c_mou_7     30001 non-null  float64
 26   loc_og_t2c_mou_8     30001 non-null  float64
 27   loc_og_mou_6         30001 non-null  float64
 28   loc_og_mou_7         30001 non-null  float64
 29   loc_og_mou_8         30001 non-null  float64
 30   std_og_t2t_mou_6     30001 non-null  float64
 31   std_og_t2t_mou_7     30001 non-null  float64
 32   std_og_t2t_mou_8     30001 non-null  float64
 33   std_og_t2m_mou_6     30001 non-null  float64
 34   std_og_t2m_mou_7     30001 non-null  float64
 35   std_og_t2m_mou_8     30001 non-null  float64
 36   std_og_t2f_mou_6     30001 non-null  float64
 37   std_og_t2f_mou_7     30001 non-null  float64
 38   std_og_t2f_mou_8     30001 non-null  float64
 39   std_og_mou_6         30001 non-null  float64
 40   std_og_mou_7         30001 non-null  float64
 41   std_og_mou_8         30001 non-null  float64
 42   isd_og_mou_6         30001 non-null  float64
 43   isd_og_mou_7         30001 non-null  float64
 44   isd_og_mou_8         30001 non-null  float64
 45   spl_og_mou_6         30001 non-null  float64
 46   spl_og_mou_7         30001 non-null  float64
 47   spl_og_mou_8         30001 non-null  float64
 48   og_others_6          30001 non-null  float64
 49   og_others_7          30001 non-null  float64
 50   og_others_8          30001 non-null  float64
 51   total_og_mou_6       30001 non-null  float64
 52   total_og_mou_7       30001 non-null  float64
 53   total_og_mou_8       30001 non-null  float64
 54   loc_ic_t2t_mou_6     30001 non-null  float64
 55   loc_ic_t2t_mou_7     30001 non-null  float64
 56   loc_ic_t2t_mou_8     30001 non-null  float64
 57   loc_ic_t2m_mou_6     30001 non-null  float64
 58   loc_ic_t2m_mou_7     30001 non-null  float64
 59   loc_ic_t2m_mou_8     30001 non-null  float64
 60   loc_ic_t2f_mou_6     30001 non-null  float64
 61   loc_ic_t2f_mou_7     30001 non-null  float64
 62   loc_ic_t2f_mou_8     30001 non-null  float64
 63   loc_ic_mou_6         30001 non-null  float64
 64   loc_ic_mou_7         30001 non-null  float64
 65   loc_ic_mou_8         30001 non-null  float64
 66   std_ic_t2t_mou_6     30001 non-null  float64
 67   std_ic_t2t_mou_7     30001 non-null  float64
 68   std_ic_t2t_mou_8     30001 non-null  float64
 69   std_ic_t2m_mou_6     30001 non-null  float64
 70   std_ic_t2m_mou_7     30001 non-null  float64
 71   std_ic_t2m_mou_8     30001 non-null  float64
 72   std_ic_t2f_mou_6     30001 non-null  float64
 73   std_ic_t2f_mou_7     30001 non-null  float64
 74   std_ic_t2f_mou_8     30001 non-null  float64
 75   std_ic_mou_6         30001 non-null  float64
 76   std_ic_mou_7         30001 non-null  float64
 77   std_ic_mou_8         30001 non-null  float64
 78   total_ic_mou_6       30001 non-null  float64
 79   total_ic_mou_7       30001 non-null  float64
 80   total_ic_mou_8       30001 non-null  float64
 81   spl_ic_mou_6         30001 non-null  float64
 82   spl_ic_mou_7         30001 non-null  float64
 83   spl_ic_mou_8         30001 non-null  float64
 84   isd_ic_mou_6         30001 non-null  float64
 85   isd_ic_mou_7         30001 non-null  float64
 86   isd_ic_mou_8         30001 non-null  float64
 87   ic_others_6          30001 non-null  float64
 88   ic_others_7          30001 non-null  float64
 89   ic_others_8          30001 non-null  float64
 90   total_rech_num_6     30001 non-null  int64
 91   total_rech_num_7     30001 non-null  int64
 92   total_rech_num_8     30001 non-null  int64
 93   total_rech_amt_6     30001 non-null  int64
 94   total_rech_amt_7     30001 non-null  int64
 95   total_rech_amt_8     30001 non-null  int64
 96   max_rech_amt_6       30001 non-null  int64
 97   max_rech_amt_7       30001 non-null  int64
 98   max_rech_amt_8       30001 non-null  int64
 99   date_of_last_rech_6  30001 non-null  datetime64[ns]
 100  date_of_last_rech_7  30001 non-null  datetime64[ns]
 101  date_of_last_rech_8  30001 non-null  datetime64[ns]
 102  last_day_rch_amt_6   30001 non-null  int64
 103  last_day_rch_amt_7   30001 non-null  int64
 104  last_day_rch_amt_8   30001 non-null  int64
 105  vol_2g_mb_6          30001 non-null  float64
 106  vol_2g_mb_7          30001 non-null  float64
 107  vol_2g_mb_8          30001 non-null  float64
 108  vol_3g_mb_6          30001 non-null  float64
 109  vol_3g_mb_7          30001 non-null  float64
 110  vol_3g_mb_8          30001 non-null  float64
 111  monthly_2g_6         30001 non-null  object
 112  monthly_2g_7         30001 non-null  object
 113  monthly_2g_8         30001 non-null  object
 114  sachet_2g_6          30001 non-null  int64
 115  sachet_2g_7          30001 non-null  int64
 116  sachet_2g_8          30001 non-null  int64
 117  monthly_3g_6         30001 non-null  object
 118  monthly_3g_7         30001 non-null  object
 119  monthly_3g_8         30001 non-null  object
 120  sachet_3g_6          30001 non-null  object
 121  sachet_3g_7          30001 non-null  object
 122  sachet_3g_8          30001 non-null  object
 123  aon                  30001 non-null  int64
 124  vbc_3g_8             30001 non-null  float64
 125  vbc_3g_7             30001 non-null  float64
 126  vbc_3g_6             30001 non-null  float64
 127  Churn                30001 non-null  object
dtypes: datetime64[ns](3), float64(99), int64(16), object(10)
memory usage: 30.5+ MB

In [73]:
num = [x for x in df.columns if (df[x].dtype == 'float64' or df[x].dtype == 'int64')]
cat = [x for x in df.columns if df[x].dtype == 'object']
date = [x for x in df.columns if x not in num+cat]

In [74]:
stop

NameError: name 'stop' is not defined

In [ ]:
df[num].describe(percentiles=[.15,0.25,0.5,0.75,0.9,0.95])

In [ ]:
from scipy import stats

In [ ]:
pd.set_option('display.max_columns',240)
df[num].apply(lambda x: (np.mean(x),stats.trim_mean(x,0.1)))

In [ ]:
corr = df[num].corr()
c = corr.unstack().reset_index()
c['corr']=abs(c[0])
c= c.sort_values(by='corr',ascending=False)
c = c[(c[0]!=1)&(c['corr']>0.7)]

In [ ]:
import matplotlib.pyplot as plt

def univariate_num(col,name='kdeplot',y=False,scale='linear',figsize=(16,8),
                   perc=[0.15,0.25,0.5,0.75,0.9,0.95],describe=False,count=False):
    
    n = len(col)
    
    plt.figure(figsize=figsize)
    for i in range(1,n):
        
        plt.subplot(1,n,i)
        m = getattr(sns,name)
        
        if y == True:
            m(data=df,y=col[i])
            
            if scale == 'log':
                plt.yscale('log')
        else:
            m(data=df,x=col[i])
        
            if scale == 'log':
                plt.xscale('log')

    
    plt.tight_layout()
    
    if describe == True:
        
        print(df[col].describe(percentiles=perc))
        
    if null == True:
        print(df[col].isnull().mean())
    
    if nunique == True:

In [ ]:
import sidetable
print(df.stb.freq([cat[0]]))

In [ ]:
col = cat
d = pd.DataFrame()
d['dtypes'] = df[col].dtypes
d['null'] = df[col].isnull().mean()
d['nunique'] = df[col].nunique()

In [ ]:
class EDA():
    
    def __init__(self,df):
        self.df = df
        
    def plot(self,col,kind='kdeplot',hue=None,y=False,scale='linear',figsize=(9,4)):
        
        
        n = len(col)

        plt.figure(figsize=figsize)
        for i in range(1,n):

            plt.subplot(1,n,i)
            m = getattr(sns,kind)

            if y == True:
                
                if (kind == 'boxplot' or kind == 'violinplot'):
                    m(data=self.df,y=col[i],x=hue)
                
                else:
                    m(data=self.df,y=col[i],hue=hue)

                if scale == 'log':
                    plt.yscale('log')
            else:
                
                if (kind == 'boxplot' or kind == 'violinplot'):
                    
                    m(data=self.df,x=col[i],y=hue)
                
                else:
                    m(data=self.df,x=col[i],hue=hue)

                if scale == 'log':
                    plt.xscale('log')

        plt.tight_layout()
        
    
    def plot_bivariate(self,col,y,kind='barplot',scale='linear',figsize=(6,7),hue=None):
        
        n = len(col)

        plt.figure(figsize=figsize)
        for i in range(1,n):

            plt.subplot(n,1,i)
            m = getattr(sns,kind)
            
            if kind == 'regplot':
                m(data=self.df,y=y,x=col[i])
              
            else:
                m(data=self.df,y=y,x=col[i],hue=hue)

            if scale == 'log':
                plt.yscale('log')
                
        plt.tight_layout()
        
    def describe(self,col,perc=[0.15,0.25,0.5,0.75,0.9,0.95]):
        
        d = pd.DataFrame()
        d['dtypes'] = self.df[col].dtypes
        d['null'] = self.df[col].isnull().mean()
        d['nunique'] = self.df[col].nunique()
        d['count'] = self.df[col].count()
        
        print('\n',self.df[col].describe(percentiles=perc))
        print('\n',d)
        
    def correlation(self,col,tol=0.7):
        
        corr = self.df[col].corr()
        c = corr.unstack().reset_index()
        c['corr']=abs(c[0])
        c= c.sort_values(by='corr',ascending=False)
        c = c[(c[0]!=1)&(c['corr']>tol)]
        c.style.backgound_gradient(cmap=Reds)
        print(c)

In [ ]:
ed = EDA(df=df)

In [ ]:
ed.plot_bivariate(col=num[:3],y=num[6],kind='regplot')

In [ ]:
!pip install -U pandas

In [ ]:
sns.boxplot(data=df,x =num[1],y='Churn' )

In [ ]:
ed.plot(col=num[:3],y=True,kind='boxplot',hue='Churn')

In [ ]:
ed.describe(col=cat)

In [ ]:
univariate_num(num[:4],scale='log')

In [ ]:
univariate_num(num[:4],name='boxplot',y=True)

In [ ]:
univariate_num(num[:4],name='boxplot',y=True,scale='log')

In [ ]:
# numerical

In [ ]:
import matplotlib.pyplot as plt

for i in num:
    
    plt.figure()
    sns.kdeplot(data=df,x=i)

In [ ]:
for i in num:
    
    plt.figure()
    sns.boxplot(data=df,y=i)

In [ ]:
for i in num:
    
    plt.figure()
    sns.violinplot(data=df,y=i)

In [ ]:
# categotical

for i in cat:
    
    plt.figure()
    sns.countplot(data=df,x=i)

In [ ]:
for i in date:
    
    plt.figure()
    sns.countplot(data=df,x=i)

In [ ]:
for i in num:
    
    plt.figure()
    sns.barplot(data=df,x='Churn',y=i)

In [ ]:
corr = df.corr()
sns.heatmap(corr,cmap='Reds')

In [ ]:
for i in cat+date:
    
    print(df[i].value_counts(normalize=True))
    print('\n ====================================================')

In [ ]:
# Preparating Data

In [ ]:
# Derived variables to measure change in usage 

# Usage 
df['delta_vol_3g'] = df['vol_3g_mb_8'] - df['vol_3g_mb_6'].add(df['vol_3g_mb_7']).div(2)
df['delta_total_og_mou'] = df['total_og_mou_8'] - df['total_og_mou_6'].add(df['total_og_mou_7']).div(2)
df['delta_total_ic_mou'] = df['total_ic_mou_8'] - df['total_ic_mou_6'].add(df['total_ic_mou_7']).div(2)
df['delta_vbc_3g'] = df['vbc_3g_8'] - df['vbc_3g_6'].add(df['vbc_3g_7']).div(2)

# Revenue 
df['delta_arpu'] = df['arpu_8'] - df['arpu_6'].add(df['arpu_7']).div(2)
df['delta_total_rech_amt'] = df['total_rech_amt_8'] - df['total_rech_amt_6'].add(df['total_rech_amt_7']).div(2)

In [ ]:
df.drop(columns=[
         'vol_2g_mb_8', 'vol_2g_mb_6', 'vol_2g_mb_7','vol_3g_mb_8'  , 'vol_3g_mb_6', 'vol_3g_mb_7' ,
        'total_og_mou_8','total_og_mou_6', 'total_og_mou_7', 'total_ic_mou_8','total_ic_mou_6', 'total_ic_mou_7',
        'vbc_3g_8','vbc_3g_6','vbc_3g_7','arpu_8','arpu_6','arpu_7','total_rech_amt_8', 'total_rech_amt_6', 'total_rech_amt_7'
    
            ], inplace=True)

In [ ]:
# outlier

pct_change = df.quantile(np.arange(0.9,1.01,0.01)).pct_change().mul(100).iloc[-1]
outlier_condition = pct_change > 100
columns_with_outliers = pct_change[outlier_condition].index.values

In [ ]:
for col in columns_with_outliers : 
    outlier_threshold = df[col].quantile(0.99)
    condition = df[col] > outlier_threshold
    df.loc[condition, col] = outlier_threshold

In [ ]:
cat.remove('Churn')
df[cat].nunique()

In [ ]:
df1 = df.copy()

In [ ]:
for col in cat : 
    category_counts = 100*df[col].value_counts(normalize=True)
    
    low_count_categories = category_counts[category_counts <= 1].index.to_list()
    
    df[col].replace(low_count_categories,'Others',inplace=True)

In [ ]:
df[cat].nunique()

In [ ]:
df.drop(columns=date,inplace=True)

In [ ]:
# dummy encoding

dummy = pd.get_dummies(df[cat], drop_first=False, prefix=cat, prefix_sep='_')
dummy.head()

In [ ]:
df.drop(columns=cat, inplace=True) # dropping original categorical columns
df = pd.concat([df, dummy], axis=1)
df.head()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Churn']),df['Churn'],
                                                    train_size=0.7, 
                                                    stratify=df['Churn'],random_state=42)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

In [ ]:
num = [x for x in X_train.columns if (X_train[x].dtype == 'float64' or 
                                      X_train[x].dtype == 'int64')]

In [ ]:
cat = [ x for x in X_train.columns if x not in num]

In [ ]:
X_train[cat] = X_train[cat].astype('int')
X_test[cat] = X_test[cat].astype('int')

In [ ]:
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [ ]:
# Standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 

# Fit and transform train set 
X_train[num] = scaler.fit_transform(X_train[num])

# Transform test set
X_test[num] = scaler.transform(X_test[num])

In [ ]:
y_train.value_counts(normalize=True)

In [ ]:
from imblearn.over_sampling import SMOTE

smt = SMOTE()
X_train_sm, y_train_sm = smt.fit_resample(X_train.values, y_train.values)

X_train_sm = pd.DataFrame(X_train_sm,columns=X_train.columns)
y_train_sm = pd.Series(y_train_sm)
X_train_sm.shape,y_train_sm.shape

In [ ]:
y_train_sm.value_counts(normalize=True)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,roc_auc_score
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

def try_diff_model(model,X_train,y_train,X_test,y_test,columns,confusion=True,
                   summary=False,vif=False):
    
    baseline_model = model # `weight of class` balancing technique used
    baseline_model = baseline_model.fit(X_train[columns], y_train)

    y_train_pred_proba = baseline_model.predict_proba(X_train[columns])[:,1]
    y_test_pred_proba  = baseline_model.predict_proba(X_test[columns])[:,1]

    y_train_pred = baseline_model.predict(X_train[columns])
    y_test_pred  = baseline_model.predict(X_test[columns])

    y_train_pred_proba = pd.Series(y_train_pred_proba,index = X_train[columns].index, ) # converting test and train to a series to preserve index
    y_test_pred_proba = pd.Series(y_test_pred_proba,index = X_test[columns].index)
    
   
    train_matrix = classification_report(y_train, y_train_pred)
    test_matrix = classification_report(y_test, y_test_pred)
    print('\nClassification report for test: \n', test_matrix)
    
   
    train_matrix = roc_auc_score(y_train, y_train_pred_proba)
    print('ROC for train:\n', train_matrix,'\n')
    test_matrix = roc_auc_score(y_test, y_test_pred_proba)
    print('\nROC for test: \n', test_matrix,'\n')
    
    if confusion == True:
        train_matrix = confusion_matrix(y_train, y_train_pred)
        print('Confusion Matrix for train:\n', train_matrix)
        test_matrix = confusion_matrix(y_test, y_test_pred)
        print('\nConfusion Matrix for test: \n', test_matrix)
    
    if summary == True:
        
        logr = sm.GLM(y_train,
              (sm.add_constant(X_train[columns])),
              family = sm.families.Binomial())
        logr_fit = logr.fit()
        print('\n',logr_fit.summary())
        
    if vif ==True:
            vif = pd.DataFrame()
            vif['Features'] = columns
            vif['VIF'] = [variance_inflation_factor(X_train[columns].values, i) 
                          for i in range(X_train[columns].shape[1])]
            vif['VIF'] = round(vif['VIF'], 2)
            vif = vif.set_index('Features')
            vif['P-value'] = round(logr_fit.pvalues,4)
            vif = vif.sort_values(by = ["VIF",'P-value'], ascending = [False,False])
            print('\n',vif)
        
    
    return y_train_pred,y_test_pred,y_train_pred_proba,y_test_pred_proba

In [ ]:
#Baseline Performance

from sklearn.linear_model import LogisticRegression

output = try_diff_model(model = LogisticRegression(random_state=100, class_weight='balanced'
                                                  ,max_iter=600),
                       X_train = X_train,y_train = y_train,
                        X_test = X_test,y_test = y_test,
                        columns=X_train.columns)

In [ ]:
#Baseline Performance on sampled df

output = try_diff_model(model=LogisticRegression(random_state=100,max_iter=1000),
                       X_train=X_train_sm,y_train=y_train_sm,
                        X_test=X_test,y_test=y_test,
                        columns=X_train_sm.columns)

In [ ]:
from sklearn.feature_selection import RFE

dic_features = {}
for i in range(20,40,2):
    
    lr = LogisticRegression(random_state=100 , class_weight='balanced',max_iter=1000)
    rfe = RFE(estimator=lr,n_features_to_select= i)
    results = rfe.fit(X_train,y_train)
    
    l =  list(results.get_feature_names_out())
    dic_features[len(l)] = l

    print('\n number of features',i)
    output = try_diff_model(LogisticRegression(random_state=100, class_weight='balanced'),
                       X_train,y_train,X_test,y_test,columns=l)
    print('====================================================================================================================================================================')

In [ ]:
# choosing  22 features as it is giving us best metrics
choosen_features = dic_features[22]

In [ ]:
output = try_diff_model(LogisticRegression(random_state=100, class_weight='balanced'),
                       X_train,y_train,X_test,y_test,columns=choosen_features,
                       confusion=False,summary=True,vif=True)

In [ ]:
# droping monthly_3g_7_0 as it has high value

In [ ]:
l = choosen_features.copy()
ll = list(set(l) - set(['monthly_3g_7_0']))

output = try_diff_model(LogisticRegression(random_state=100, class_weight='balanced'),
                       X_train,y_train,X_test,y_test,columns=ll,
                       confusion=False,summary=True,vif=True)

In [ ]:
# dropping monthly_2g_6_0 witch as high pvalue

l = choosen_features.copy()
ll = list(set(l) - set(['monthly_3g_7_0','monthly_2g_6_0']))

output = try_diff_model(LogisticRegression(random_state=100, class_weight='balanced'),
                       X_train,y_train,X_test,y_test,columns=ll,
                       confusion=False,summary=True,vif=True)

In [ ]:
#droping sachet_3g_6_0 which has high p value

l = choosen_features.copy()
ll = list(set(l) - set(['monthly_3g_7_0','monthly_2g_6_0','sachet_3g_6_0']))

output = try_diff_model(LogisticRegression(random_state=100, class_weight='balanced'),
                       X_train,y_train,X_test,y_test,columns=ll,
                       confusion=False,summary=True,vif=True)

In [ ]:
#droping monthly_2g_8_0,monthly_2g_7_0 which has high vif


l = choosen_features.copy()
ll = list(set(l) - set(['monthly_3g_7_0','monthly_2g_6_0','sachet_3g_6_0','monthly_2g_8_0','monthly_2g_7_0']))

output = try_diff_model(LogisticRegression(random_state=100, class_weight='balanced'),
                       X_train,y_train,X_test,y_test,columns=ll,
                       confusion=False,summary=True,vif=True)

In [ ]:
# build model using pca
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=0.95,random_state=100)
pca.fit(X_train_sm)

In [ ]:
np.sum(pca.explained_variance_ratio_)

In [ ]:
len(pca.explained_variance_ratio_)

In [ ]:
pca = PCA(n_components=60,random_state=100)
pca.fit(X_train_sm)

In [ ]:
X_train_pca  = pca.transform(X_train_sm)
X_test_pca  = pca.transform(X_test)

In [ ]:
col = [f'PCA_{i}' for i in range(1,61)]

X_train_pca = pd.DataFrame(X_train_pca,columns=col)
X_test_pca = pd.DataFrame(X_test_pca,columns=col)

In [ ]:
sns.scatterplot(x=X_train_pca['PCA_1'],y=X_train_pca['PCA_2'],hue=y_train_sm)

In [ ]:
output = try_diff_model(LogisticRegression(random_state=100),
                       X_train_pca,y_train_sm,X_test_pca,y_test,columns=X_train_pca.columns,
                      )

In [ ]:
# tring different models

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

In [ ]:
dt = DecisionTreeClassifier(random_state=100,max_depth=10)

output = try_diff_model(dt,
                       X_train_pca,y_train_sm,X_test_pca,y_test,columns=X_train_pca.columns,
                      )

In [ ]:
rf = RandomForestClassifier(random_state=100,max_depth=10)

output = try_diff_model(rf,
                       X_train_pca,y_train_sm,X_test_pca,y_test,columns=X_train_pca.columns,
                      )

In [ ]:
gb = GradientBoostingClassifier(random_state=100,max_depth=8,min_samples_leaf=6)

output = try_diff_model(gb,
                       X_train_pca,y_train_sm,X_test_pca,y_test,columns=X_train_pca.columns,
                      )

In [ ]:
from sklearn.model_selection import  GridSearchCV

In [ ]:
params = dict(
            max_depth = [7,10],
            n_estimators=[50,100],
            min_samples_split=[2,4],
            min_samples_leaf=[1,2]
)

gs = GridSearchCV(RandomForestClassifier(random_state=100),params,cv=5,
                 scoring='roc_auc')

In [ ]:
gs.fit(X_train_pca,y_train_sm)

In [ ]:
gs.best_score_

In [ ]:
gs.best_params_

In [ ]:
para = {'max_depth': 20,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 150}

In [ ]:
output = try_diff_model(RandomForestClassifier(random_state=100,**para),
                       X_train_pca,y_train_sm,X_test_pca,y_test,columns=X_train_pca.columns,
                      )

In [1]:
from sklearn.model_selection import GridSearchCV

In [ ]:
GridSearchCV()